### ISSUE TITLE
Task:Classifying Generated Tupes

### ISSUE THREAD

**Issue by Nostalgia0714** [atcbosselut/comet-commonsense#27]
Hi, I want to implement the task ‘Classifying Generated Tupes’, I have the following questions:

1. Can the experiment be run under the windows system?

2. What version of torch is used for this task? The pytorch official website does not provide a version of the windows system corresponding to python2.7.

3. The interface when running the command ‘bash scripts/classify/classify.sh’,has no result.

**Comment by atcbosselut** [comment]
1) It should be possible to run it if you install bash for windows. But it's a bash script, so it probably won't natively run on windows.

2) I don't think classify.sh requires pytorch. If it does, then it should the same version as the rest of the repo -- >= 1.0

3) Then it's probably not working since the script writes to stdout
